/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IBadERC721 } from "../IBadERC721";

export class IBadERC721__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IBadERC721 {
    return new Contract(address, _abi, signerOrProvider) as IBadERC721;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "transfer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
